services:
  web:
    container_name: nextjs-web
    image: web:latest
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file:
      - ./apps/web/.env
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOSTNAME=0.0.0.0
      - BASE_URL=http://localhost
      - LOF_FORMAT=text
    stop_signal: SIGINT
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
