name: "Google Cloud Authentication"

on:
  workflow_call:
    secrets:
      google_cloud_project_id:
        required: true
      google_cloud_project_number:
        required: true
      workload_identity_pool_id:
        required: true
      workload_identity_provider_id:
        required: true
      service_account:
        required: true
    outputs:
      access_token:
        value: ${{ jobs.auth.outputs.access_token }}

jobs:
  auth-google-cloud:
    runs-on: ubuntu-latest
    outputs:
      access_token: ${{ steps.auth.outputs.access_token }}
    steps:
      - uses: google-github-actions/auth@v1
        id: auth
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.google_cloud_project_number }}/locations/global/workloadIdentityPools/${{ secrets.workload_identity_pool_id }}/providers/${{ secrets.workload_identity_provider_id }}"
          service_account: "${{ secrets.service_account }}"
          project_id: "${{ secrets.google_cloud_project_id }}"
