name: Cleanup

on:
  pull_request:
    types: [closed]

  workflow_dispatch:
    inputs:
      artifact_repository:
        description: "Delete all build images in the Google cloud artifact repository for the specified branch"
        type: boolean
        default: false
      github_cache:
        description: "Delete all Github caches for the specified branch"
        type: boolean
        default: true
      execute_cloudrun_revision:
        description: "Remove from Cloudrun revisions"
        type: boolean
        default: false

jobs:
  get-config:
    name: Get Config
    uses: ./.github/workflows/get-config.yml

  check-param:
    runs-on: ubuntu-latest
    name: Check Parameter
    needs: [get-config]
    timeout-minutes: 1
    steps:
      - name: Check param
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ needs.get-config.outputs.ref_name_lowercase }}" == "main" ]; then 

              ## DockerImage in production environment cannot be deleted
              if [ "${{ github.event.inputs.artifact_repository }}" == "true" ]; then
                echo "::error::Cannot cleanup to main branch directly via workflow_dispatch"
                exit 1
              fi

              ## Revision Tag in production environment cannot be deleted
              if [ "${{ github.event.inputs.execute_cloudrun_revision }}" == "true" ]; then
                echo "::error::Cannot cleanup to main branch directly via workflow_dispatch"
                exit 1
              fi
            fi
          fi

  web:
    name: Web
    permissions:
      id-token: write
      contents: read
    needs: [get-config, check-param]
    if: |
      always() &&
      needs.get-config.result == 'success' &&
      needs.check-param.result == 'success'
    uses: ./.github/workflows/cleanup-common.yml
    with:
      environment: ${{ needs.get-config.outputs.environment }}
      app: web
      app_name: ${{ needs.get-config.outputs.app_name }}
      app_version: ${{ needs.get-config.outputs.web_lowercase_version }}
      repo_name: ${{ needs.get-config.outputs.repo_name_lowercase }}
      ref_name: ${{ needs.get-config.outputs.ref_name_lowercase }}
      execute_artifact_repository: ${{ github.event_name == 'pull_request' || github.event.inputs.artifact_repository == 'true' }}
      execute_cloudrun_revision: ${{ github.event_name == 'pull_request' || github.event.inputs.execute_cloudrun_revision == 'true' }}
      execute_github_cache: ${{ github.event_name == 'pull_request' || github.event.inputs.github_cache == 'true' }}
    secrets: inherit

  api:
    name: Api
    permissions:
      id-token: write
      contents: read
    needs: [get-config, check-param]
    if: |
      always() &&
      needs.get-config.result == 'success' &&
      needs.check-param.result == 'success'
    uses: ./.github/workflows/cleanup-common.yml
    with:
      environment: ${{ needs.get-config.outputs.environment }}
      app: api
      app_name: ${{ needs.get-config.outputs.app_name }}
      app_version: ${{ needs.get-config.outputs.api_lowercase_version }}
      repo_name: ${{ needs.get-config.outputs.repo_name_lowercase }}
      ref_name: ${{ needs.get-config.outputs.ref_name_lowercase }}
      execute_artifact_repository: ${{ github.event_name == 'pull_request' || github.event.inputs.artifact_repository == 'true' }}
      execute_cloudrun_revision: ${{ github.event_name == 'pull_request' || github.event.inputs.execute_cloudrun_revision == 'true' }}
      execute_github_cache: ${{ github.event_name == 'pull_request' || github.event.inputs.github_cache == 'true' }}
    secrets: inherit
