name: Convert to Lowercase

on:
  workflow_call:
    inputs:
      text:
        required: true
        type: string

jobs:
  convert:
    runs-on: ubuntu-latest
    outputs:
      lowercase_text: ${{ steps.convert_text.outputs.lowercase_text }}
    steps:
      - name: Convert text to lowercase
        id: convert_text
        run: echo "lowercase_text=${{ inputs.text,, }}" >> $GITHUB_OUTPUT
