name: "Deployment"

on:
  push:
    branches: [main, stage, develop]
    paths:
      - "apps/web/**"
      - "apps/api/**"
      - "packages/critters/**"
      - "packages/ui/**"

  workflow_dispatch:

env:
  ## Common
  GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
  GOOGLE_CLOUD_PROJECT_NUMBER: ${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}
  GOOGLE_CLOUD_IDENTITY_POOL_ID: ${{ secrets.GOOGLE_CLOUD_IDENTITY_POOL_ID }}
  GOOGLE_CLOUD_IDENTITY_PROVIDER_ID: ${{ secrets.GOOGLE_CLOUD_IDENTITY_PROVIDER_ID }}

  ## Web
  BASE_URL: ${{ secrets.BASE_URL }}

  ## Api
  MONGODB_USER_NAME: ${{ secrets.MONGODB_USER_NAME }}
  MONGODB_USER_PASSWORD: ${{ secrets.MONGODB_USER_PASSWORD }}
  MONGODB_HOST_NAME: ${{ secrets.MONGODB_HOST_NAME }}

jobs:
  get-config:
    name: Get Config
    uses: ./.github/workflows/get-config.yml
    with:
      trigger: ${{ github.event_name }}

  check-param:
    runs-on: ubuntu-latest
    name: Check Parameter
    needs: [get-config]
    steps:
      - name: Check param
        run: |
          if [ "${{ github.event_name }}" == 'workflow_dispatch' ]; then
            if [ "${{ needs.get-config.outputs.ref_name_lowercase }}" == "main" ] || \
               [ "${{ needs.get-config.outputs.ref_name_lowercase }}" == "develop" ] || \
               [ "${{ needs.get-config.outputs.ref_name_lowercase }}" == "stage" ]; then
              echo "::error::Cannot deploy to main, develop, or stage branch directly via workflow_dispatch"
              exit 1
            fi
          fi

  deploy-web:
    name: Web
    needs: [get-config, get-change-paths]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deployment-common.yml
    with:
      environment: ${{ needs.get-config.outputs.environment }}
      app: web
      app_name: ${{ needs.get-config.outputs.app_name }}
      app_version: ${{ needs.get-config.outputs.web_lowercase_version }}
      repo_name: ${{ needs.get-config.outputs.repo_name_lowercase }}
      ref_name: ${{ needs.get-config.outputs.ref_name_lowercase }}
    secrets: inherit

  deploy-api:
    name: Api
    needs: [get-config, get-change-paths]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deployment-common.yml
    with:
      environment: ${{ needs.get-config.outputs.environment }}
      app: api
      app_name: ${{ needs.get-config.outputs.app_name }}
      app_version: ${{ needs.get-config.outputs.api_lowercase_version }}
      repo_name: ${{ needs.get-config.outputs.repo_name_lowercase }}
      ref_name: ${{ needs.get-config.outputs.ref_name_lowercase }}
    secrets: inherit
