name: "Deploy CloudRun"

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      environment:
        required: true
        type: string
      ref_name:
        required: true
        type: string
      google_cloud_region:
        required: true
        type: string
      google_cloud_service_env:
        required: true
        type: string
    secrets:
      google_cloud_project_id:
        required: true
      google_cloud_project_number:
        required: true
      google_cloud_workload_identity_pool_id:
        required: true
      google_cloud_workload_identity_provider_id:
        required: true
      google_cloud_service_account:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.google_cloud_project_number }}/locations/global/workloadIdentityPools/${{ secrets.google_cloud_workload_identity_pool_id }}/providers/${{ secrets.google_cloud_workload_identity_provider_id }}"
          service_account: "${{ secrets.google_cloud_service_account }}"
          project_id: "${{ secrets.google_cloud_project_id }}"

      - name: Create Service declaration
        run: |
          export CONTAINER_IMAGE="${{ inputs.google_cloud_region }}-docker.pkg.dev/${{ secrets.google_cloud_project_id }}/${{ inputs.repo_name }}/${{ inputs.app }}/${{ inputs.google_cloud_service_env }}:${{ github.sha }}"
          export SERVICE_NAME="${{ inputs.app_name }}-${{ inputs.app }}-${{ inputs.google_cloud_service_env }}"
          export PROJECT_ID="${{ secrets.google_cloud_project_id }}"
          export REVISION_TAG="${{ github.sha }}/${{ inputs.ref_name }}"
          export CLOUD_RUN_SA="${{ secrets.google_cloud_service_account }}"
          export ENVIRONMENT="${{ inputs.environment }}"
          envsubst < ./apps/${{ inputs.app }}/service.yaml > service-${{ inputs.environment }}.yaml

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ inputs.app_name }}-${{ inputs.app }}-${{ inputs.google_cloud_service_env }}
          region: ${{ inputs.google_cloud_region }}
          metadata: service-${{ inputs.environment }}.yaml
          project_id: ${{ secrets.google_cloud_project_id }}
