name: "Deploy"

on:
  push:
    branches: [main, stage, develop, feat/deploy-google-cloud]
    # paths:
    #   - "apps/web/**"
    #   - "packages/critters/**"
    #   - "packages/ui/**"

  #WARN: Temporary permission
  workflow_dispatch:

env:
  ## Common
  GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
  GOOGLE_CLOUD_PROJECT_NUMBER: ${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}
  GOOGLE_CLOUD_IDENTITY_POOL_ID: ${{ secrets.GOOGLE_CLOUD_IDENTITY_POOL_ID }}
  GOOGLE_CLOUD_IDENTITY_PROVIDER_ID: ${{ secrets.GOOGLE_CLOUD_IDENTITY_PROVIDER_ID }}

  ## Web
  BASE_URL: ${{ secrets.BASE_URL }}

  ## Api
  MONGODB_USER_NAME: ${{ secrets.MONGODB_USER_NAME }}
  MONGODB_USER_PASSWORD: ${{ secrets.MONGODB_USER_PASSWORD }}
  MONGODB_HOST_NAME: ${{ secrets.MONGODB_HOST_NAME }}

jobs:
  get-config:
    name: Get Config
    uses: ./.github/workflows/prepare-deploy.yml
    with:
      trigger: ${{ github.event_name }}

  deploy-web:
    name: Web
    needs: [get-config]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-common.yml
    with:
      environment: ${{ needs.get-config.outputs.environment }}
      app: web
      app_name: ${{ needs.get-config.outputs.app_name }}
      app_version: ${{ needs.get-config.outputs.web_lowercase_version }}
      repo_name: ${{ needs.get-config.outputs.repo_name_lowercase }}
      ref_name: ${{ needs.get-config.outputs.ref_name_lowercase }}
      google_cloud_region: ${{ vars.GOOGLE_CLOUD_REGION }}
      google_cloud_service_env: ${{ github.event_name == 'push' && needs.get-config.outputs.environment || format('pre-{0}', needs.get-config.outputs.ref_name_lowercase) }}
    secrets: inherit

  deploy-api:
    name: Api
    needs: [get-config]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/deploy-common.yml
    with:
      environment: ${{ needs.get-config.outputs.environment }}
      app: api
      app_name: ${{ needs.get-config.outputs.app_name }}
      app_version: ${{ needs.get-config.outputs.web_lowercase_version }}
      repo_name: ${{ needs.get-config.outputs.repo_name_lowercase }}
      ref_name: ${{ needs.get-config.outputs.ref_name_lowercase }}
      google_cloud_region: ${{ vars.GOOGLE_CLOUD_REGION }}
      google_cloud_service_env: ${{ github.event_name == 'push' && needs.get-config.outputs.environment || format('pre-{0}', needs.get-config.outputs.ref_name_lowercase) }}
    secrets: inherit
