name: "Deploy Next.js"

on:
  push:
    branches: [main, stage, develop]

env:
  GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
  GOOGLE_CLOUD_PROJECT_NUMBER: ${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}
  GOOGLE_CLOUD_IDENTITY_POOL_ID: ${{ secrets.GOOGLE_CLOUD_IDENTITY_POOL_ID }}
  GOOGLE_CLOUD_IDENTITY_PROVIDER_ID: ${{ secrets.GOOGLE_CLOUD_IDENTITY_PROVIDER_ID }}

  BASE_URL: ${{ secrets.BASE_URL }}

jobs:
  prepare:
    name: Prepare Web
    uses: ./.github/workflows/prepare-deploy.yml
    with:
      trigger: ${{ github.event_name }}

  prepare-google-cloud:
    name: Prepare web with google cloud
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    needs: prepare
    uses: ./.github/workflows/prepare-google-cloud.yml
    with:
      action: deploy
      repo_name: ${{ needs.prepare.outputs.repo_name_lowercase }}
      google_cloud_region: ${{ vars.GOOGLE_CLOUD_REGION }}
    secrets:
      google_cloud_project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      google_cloud_project_number: ${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}
      google_cloud_workload_identity_pool_id: ${{ secrets.GOOGLE_CLOUD_IDENTITY_POOL_ID }}
      google_cloud_workload_identity_provider_id: ${{ secrets.GOOGLE_CLOUD_IDENTITY_PROVIDER_ID }}
      google_cloud_service_account: ${{ needs.prepare.outputs.app_name }}-app-sa@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com

  build:
    name: Build web with docker
    needs:
      - prepare
      - prepare-google-cloud
    uses: ./.github/workflows/docker-build.yml
    with:
      action: "build-and-push"
      repo_name: ${{ needs.prepare.outputs.repo_name_lowercase }}
      google_cloud_region: ${{ vars.GOOGLE_CLOUD_REGION }}
      google_cloud_service_env: ${{ github.event_name == 'push' && needs.prepare.outputs.environment || format('pre-{0}', needs.prepare.outputs.ref_name_lowercase) }}
      google_cloud_access_token: ${{ needs.prepare-google-cloud.outputs.access_token }}
      app: web
      app_version: ${{ needs.prepare.outputs.web_lowercase_version }}
    secrets:
      google_cloud_project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}

  deploy:
    name: Deploy web to cloudrun
    needs:
      - prepare
      - prepare-google-cloud
      - build
    uses: ./.github/workflows/deploy-google-cloud-run.yml
    with:
      app_name: ${{ needs.prepare.outputs.app_name }}
      app: web
      environment: ${{ needs.prepare.outputs.environment }}
      ref_name: ${{ needs.prepare.outputs.ref_name_lowercase }}
      google_cloud_region: ${{ vars.GOOGLE_CLOUD_REGION }}
      google_cloud_service_env: ${{ github.event_name == 'push' && needs.prepare.outputs.environment || format('pre-{0}', needs.prepare.outputs.ref_name_lowercase) }}
      docker_image: ${{ needs.build.outputs.docker_image }}
    secrets:
      google_cloud_project_id: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      google_cloud_service_account: ${{ needs.prepare.outputs.app_name }}-app-sa@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com
