on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app:
        required: true
        type: string
      app_name:
        required: true
        type: string
      app_version:
        required: true
        type: string
      repo_name:
        required: true
        type: string
      ref_name:
        required: true
        type: string
      google_cloud_region:
        required: true
        type: string
      google_cloud_service_env:
        required: true
        type: string

jobs:
  cloudrun:
    name: Destroy CloudRun Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auth GoogleCloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GOOGLE_CLOUD_IDENTITY_POOL_ID }}/providers/${{ secrets.GOOGLE_CLOUD_IDENTITY_PROVIDER_ID }}"
          service_account: "${{ inputs.app_name }}-app-sa@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com"
          project_id: "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}"

      - name: Check CloudRun Service
        id: check
        run: |
          if gcloud run services describe ${{ inputs.app_name }}-${{ inputs.app }}-${{ inputs.google_cloud_service_env }} --region=${{ inputs.google_cloud_region }} --project=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}; then
            echo "is_created=true" >> $GITHUB_OUTPUT
          else
            echo "is_created=false" >> $GITHUB_OUTPUT
          fi

      - name: Destroy Cloud Run service
        id: destroy
        if: steps.check.outputs.is_created == 'true'
        run: |
          gcloud run services delete ${{ inputs.app_name }}-${{ inputs.app }}-${{ inputs.google_cloud_service_env }} --region ${{ inputs.google_cloud_region }} --quiet

  artifact-repository:
    name: Delete Artifact Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auth GoogleCloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GOOGLE_CLOUD_IDENTITY_POOL_ID }}/providers/${{ secrets.GOOGLE_CLOUD_IDENTITY_PROVIDER_ID }}"
          service_account: "${{ inputs.app_name }}-app-sa@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com"
          project_id: "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}"

      - name: Generate Image
        id: generate_image
        run: |
          IMAGE_NAME="${{ inputs.google_cloud_region }}-docker.pkg.dev/${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}/${{ inputs.repo_name }}/${{ inputs.app }}/${{ inputs.google_cloud_service_env }}"
          echo "docker_image=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Remove Docker Images
        id: remove_docker_images
        run: |
          # List images in the Artifact Registry
          hashs=$(gcloud artifacts docker images list ${{ steps.generate_image.outputs.docker_image }} --include-tags --format="get(metadata.name)" --project ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }})

          # Loop through each image and delete it
          if [ -n "$hashs" ]; then
            for hash in $hashs; do
              gcloud artifacts docker images delete "${{ steps.generate_image.outputs.docker_image }}@$hash" --delete-tags --project=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }} --quiet
              echo "Remove: ${{ steps.generate_image.outputs.docker_image }}@$hash"
            done

            gcloud artifacts docker images delete "${{ steps.generate_image.outputs.docker_image }}" --delete-tags --project=${{ secrets.GOOGLE_CLOUD_PROJECT_ID }} --quiet
          fi

  build-cache:
    name: Delete Build Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete GitHub Actions Cache
        run: |
          gh extension install actions/gh-actions-cache

          REPO="${{ github.repository }}"
          BRANCH="${{ inputs.ref_name }}"

          echo "Fetching list of cache key"
          cacheKeys=$(gh actions-cache list -R $REPO -B $BRANCH | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ github.token }}

  load-balancer:
    name: Cleanup LoadBalancer Resources
    runs-on: ubuntu-latest
    steps:
      - name: Auth GoogleCloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: "access_token"
          workload_identity_provider: "projects/${{ secrets.GOOGLE_CLOUD_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ secrets.GOOGLE_CLOUD_IDENTITY_POOL_ID }}/providers/${{ secrets.GOOGLE_CLOUD_IDENTITY_PROVIDER_ID }}"
          service_account: "${{ inputs.app_name }}-app-sa@${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}.iam.gserviceaccount.com"
          project_id: "${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}"

      - name: Remove Domain Mapping
        if: vars.DOMAIN != ''
        run: |
          gcloud beta run domain-mappings delete \
            --domain "${{ vars.DOMAIN }}" \
            --region "${{ inputs.google_cloud_region }}" \
            --quiet

      - name: Remove Forwarding Rules
        run: |
          gcloud compute forwarding-rules delete "${{ inputs.app_name }}-${{ inputs.google_cloud_service_env }}-http-forwarding-rule" \
            --global \
            --quiet || true
          gcloud compute forwarding-rules delete "${{ inputs.app_name }}-${{ inputs.google_cloud_service_env }}-https-forwarding-rule" \
            --global \
            --quiet || true

      - name: Remove HTTP/HTTPS Proxies
        run: |
          gcloud compute target-http-proxies delete "${{ inputs.app_name }}-${{ inputs.google_cloud_service_env }}-http" \
            --global \
            --quiet || true
          gcloud compute target-https-proxies delete "${{ inputs.app_name }}-${{ inputs.google_cloud_service_env }}-https" \
            --global \
            --quiet || true

      - name: Remove SSL Certificate
        run: |
          gcloud compute ssl-certificates delete "${{ inputs.app_name }}-${{ inputs.google_cloud_service_env }}" \
            --global \
            --quiet || true

      - name: Remove URL Map
        run: |
          gcloud compute url-maps delete "${{ inputs.app_name }}-${{ inputs.google_cloud_service_env }}-load-balancer" \
            --global \
            --quiet || true

      - name: Remove Backend Services
        run: |
          gcloud compute backend-services delete "${{ inputs.app_name }}-web-${{ inputs.google_cloud_service_env }}-backend" \
            --global \
            --quiet || true
          gcloud compute backend-services delete "${{ inputs.app_name }}-api-${{ inputs.google_cloud_service_env }}-backend" \
            --global \
            --quiet || true

      - name: Remove Network Endpoint Groups
        run: |
          gcloud compute network-endpoint-groups delete "${{ inputs.app_name }}-web-${{ inputs.google_cloud_service_env }}-neg" \
            --region "${{ inputs.google_cloud_region }}" \
            --quiet || true
          gcloud compute network-endpoint-groups delete "${{ inputs.app_name }}-api-${{ inputs.google_cloud_service_env }}-neg" \
            --region "${{ inputs.google_cloud_region }}" \
            --quiet || true
