name: Destroy

on:
  pull_request:
    types: [closed]

jobs:
  destroy-web:
    name: Destroy Web
    if: github.event.pull_request.head.ref != 'refs/heads/main' && github.event.pull_request.head.ref != 'refs/heads/develop' && github.event.pull_request.head.ref != 'refs/heads/stage'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/destroy-app.yml
    with:
      app: web
    secrets: inherit

  destroy-api:
    name: Destroy Api
    if: github.event.pull_request.head.ref != 'refs/heads/main' && github.event.pull_request.head.ref != 'refs/heads/develop' && github.event.pull_request.head.ref != 'refs/heads/stage'
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/destroy-app.yml
    with:
      app: api
    secrets: inherit
