name: "Build and Push With Docker"

on:
  workflow_call:
    inputs:
      repo_name:
        required: true
        type: string
      google_cloud_region:
        required: true
        type: string
      google_cloud_service_env:
        required: true
        type: string
      google_cloud_access_token:
        required: true
        type: string
      app:
        required: true
        type: string
      app_version:
        required: true
        type: string
    secrets:
      google_cloud_project_id:
        required: true
    outputs:
      docker_image:
        value: ${{ jobs.generate-image.outputs.docker_image }}

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest
    outputs:
      docker_image: ${{ steps.generate_image.outputs.docker_image }}
    steps:
      - name: Authenticate with Docker
        uses: docker/login-action@v1
        with:
          username: "oauth2accesstoken"
          password: "${{ inputs.google_cloud_access_token }}"
          registry: "${{ inputs.google_cloud_region }}-docker.pkg.dev"

      - name: Generate Image
        id: generate_image
        run: |
          IMAGE_NAME="${{ inputs.google_cloud_region }}-docker.pkg.dev/${{ secrets.google_cloud_project_id }}/${{ inputs.repo_name }}/${{ inputs.app }}/${{ inputs.google_cloud_service_env }}"
          echo "docker_image=${IMAGE_NAME}" >> $GITHUB_OUTPUT

      - name: Build, tag, and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./apps/${{ inputs.app }}/Dockerfile
          push: true
          tags: |
            ${{ steps.generate_docker_image.outputs.docker_image }}:${{ inputs.app_version }}
            ${{ steps.generate_docker_image.outputs.docker_image }}:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      ## [issue](https://github.com/docker/build-push-action/issues/252)
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
